import Link from "next/link";

import { EditorialPlaceholder } from "@/components/media/editorial-placeholder";
import { ArrowLink } from "@/components/ui/arrow-link";
import { prizeCategories } from "@/content/fallback/site";
import type { Collection, Designer, FashionWeekEdition, Partner, ScheduleEvent } from "@/types/content";
import { HomeMotion } from "@/animation/gsap/home-motion";

import { HeroMotion } from "./hero-motion";

export function HomePage({ edition, designers, collections, schedule, partners }: { edition: FashionWeekEdition; designers: Designer[]; collections: Collection[]; schedule: ScheduleEvent[]; partners: Partner[] }) {
  return <HomeMotion>
    <section className="editorial-grid relative flex min-h-[100svh] items-end overflow-hidden bg-asoebi-ink px-5 pb-10 pt-28 text-white lg:px-10 lg:pb-14">
      <div className="absolute inset-0"><div data-hero-atmosphere className="absolute -right-[8%] top-[12%] h-[68%] w-[60%] rotate-[-7deg] bg-gradient-to-br from-asoebi-purple-500/55 via-asoebi-purple-900/25 to-transparent blur-3xl"/><div data-hero-line className="absolute left-[58%] top-[20%] h-[56%] w-[2px] rotate-[18deg] bg-asoebi-gold-400"/></div>
      <div className="mx-auto w-full max-w-[1600px]"><HeroMotion>
        <p data-hero-eyebrow className="mb-5 text-[11px] font-semibold uppercase tracking-[.24em] text-asoebi-purple-200">Fashion · Textiles · Culture · Celebration</p>
        <h1 className="font-display max-w-[15ch] text-[clamp(4.3rem,12vw,12rem)] leading-[.74] tracking-[-.075em]"><span data-hero-title-line className="block">ASOEBI</span><span data-hero-title-line className="ml-[8vw] block italic text-asoebi-purple-300">Fashion</span><span data-hero-title-line className="block">Week</span></h1>
        <div data-hero-support className="mt-10 grid gap-8 border-t border-white/20 pt-6 md:grid-cols-[1fr_1fr] lg:ml-[40%]"><p className="max-w-xl text-lg leading-7 text-white/72">{edition.description}</p><div className="flex flex-wrap gap-5"><Link href="/tickets" className="bg-white px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-asoebi-ink">Get Tickets</Link><ArrowLink href="/fashion-week" inverse>Explore Fashion Week</ArrowLink></div></div>
      </HeroMotion></div>
    </section>

    <section className="bg-asoebi-paper px-5 py-28 lg:px-10 lg:py-44"><div className="mx-auto max-w-[1600px]"><div className="grid gap-14 lg:grid-cols-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand lg:col-span-3">Our manifesto</p><div className="lg:col-span-9"><h2 data-motion-reveal className="font-display text-[clamp(3.3rem,8vw,8.5rem)] leading-[.82] tracking-[-.06em]">Where Asoebi<br/><span className="italic text-brand">takes the global</span><br/>stage.</h2><p data-motion-reveal className="mt-10 max-w-2xl text-lg leading-8 text-asoebi-graphite">Asoebi Fashion Week brings designers, textiles, craftsmanship, culture and community together through a global celebration of African fashion.</p></div></div></div></section>

    <section className="overflow-hidden bg-asoebi-purple-950 py-24 text-white lg:py-36"><div className="mx-auto max-w-[1600px] px-5 lg:px-10"><div data-motion-reveal className="flex items-end justify-between gap-8"><div><p className="text-xs uppercase tracking-[.18em] text-asoebi-purple-300">Meet the makers</p><h2 className="font-display mt-4 text-6xl tracking-[-.06em] sm:text-8xl">The Designers</h2></div><ArrowLink href="/designers" inverse>View all</ArrowLink></div><div className="mt-16 grid gap-8 md:grid-cols-3">{designers.map((designer, index) => <Link data-motion-media href={`/designers/${designer.slug}`} key={designer.slug} className={`group ${index === 1 ? "md:mt-24" : ""}`}><EditorialPlaceholder label={designer.name} tone={designer.visualTone} className="aspect-[3/4] transition-transform duration-700 group-hover:scale-[.985]"/><div className="flex items-start justify-between border-t border-white/20 pt-4"><div><h3 className="text-xl font-semibold">{designer.name}</h3><p className="mt-1 text-xs text-white/55">{designer.location}</p></div><span aria-hidden="true">↗</span></div></Link>)}</div></div></section>

    <section className="bg-asoebi-ivory px-5 py-28 lg:px-10 lg:py-40"><div className="mx-auto max-w-[1600px]"><div data-motion-reveal className="grid gap-10 lg:grid-cols-2"><h2 className="font-display text-6xl leading-[.85] tracking-[-.06em] sm:text-8xl">On the<br/><span className="italic text-brand">schedule</span></h2><p className="max-w-md self-end text-lg text-asoebi-graphite">Runway shows, conversations and cultural moments—one programme.</p></div><div className="mt-16 border-t border-asoebi-ink">{schedule.map((event) => <article data-motion-row key={event.id} className="grid gap-4 border-b border-asoebi-ink/25 py-7 md:grid-cols-[1fr_10rem] md:items-center"><div><h3 className="text-2xl font-semibold uppercase tracking-[-.02em]">{event.title}</h3><p className="mt-2 text-sm text-asoebi-muted">{event.description}</p></div><p className="text-xs font-bold uppercase tracking-[.16em]">{event.type}</p></article>)}</div><div className="mt-8"><ArrowLink href="/fashion-week/schedule">View full schedule</ArrowLink></div></div></section>

    <section className="bg-asoebi-paper px-5 py-28 lg:px-10 lg:py-40"><div className="mx-auto max-w-[1600px]"><div data-motion-reveal><p className="text-xs font-bold uppercase tracking-[.18em] text-brand">From the runway</p><h2 className="font-display mt-5 max-w-4xl text-6xl leading-[.85] tracking-[-.06em] sm:text-9xl">Stories told<br/>in <span className="italic">cloth.</span></h2></div><div className="mt-16 grid gap-10 lg:grid-cols-12">{collections.map((collection, index) => <Link data-motion-media href={`/collections/${collection.slug}`} key={collection.slug} className={`${index === 0 ? "lg:col-span-5" : index === 1 ? "lg:col-span-4 lg:mt-32" : "lg:col-span-3 lg:mt-10"}`}><EditorialPlaceholder label={collection.title} tone={collection.visualTone} className={index === 1 ? "aspect-[4/5]" : "aspect-[3/4]"}/><h3 className="mt-4 text-lg font-bold uppercase">{collection.title}</h3><p className="mt-1 text-xs text-asoebi-muted">Collection notes coming soon</p></Link>)}</div><div className="mt-12"><ArrowLink href="/collections">Explore collections</ArrowLink></div></div></section>

    <section className="bg-asoebi-gold-100 px-5 py-28 lg:px-10 lg:py-40"><div className="mx-auto grid max-w-[1600px] gap-14 lg:grid-cols-2"><div data-motion-reveal><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-gold-800">Prestige · Recognition · Impact</p><h2 className="font-display mt-5 text-7xl tracking-[-.07em] sm:text-9xl">Asoebi<br/><span className="italic">Prize</span></h2><p className="mt-8 max-w-md text-lg leading-8">The premier annual award celebrating creativity in African fashion.</p><div className="mt-8"><ArrowLink href="/prize">Discover the prize</ArrowLink></div></div><ul data-motion-list className="self-end border-t border-asoebi-gold-950">{prizeCategories.map((category) => <li key={category} className="border-b border-asoebi-gold-950/30 py-6 text-xl font-semibold">{category}</li>)}</ul></div></section>

    <section className="overflow-hidden bg-asoebi-paper px-5 py-28 lg:px-10 lg:py-44"><div className="mx-auto max-w-[1600px]"><h2 data-motion-reveal className="font-display text-[clamp(4rem,10vw,10rem)] leading-[.78] tracking-[-.07em]">More than<br/><span className="ml-[12vw] italic text-brand">a runway.</span></h2><div data-motion-ribbon className="mt-16 flex flex-wrap gap-x-8 gap-y-3 border-y border-asoebi-ink py-7 text-xl font-semibold uppercase sm:text-3xl">{["Fashion", "Textiles", "Craft", "Culture", "Music", "Community", "Conversation", "Celebration"].map((item) => <span key={item} className="after:ml-8 after:text-asoebi-purple-400 after:content-['✦']">{item}</span>)}</div></div></section>

    <section data-motion-night className="relative overflow-hidden bg-asoebi-ink px-5 py-32 text-white lg:px-10 lg:py-52"><div data-motion-night-glow className="absolute right-[-10%] top-[-20%] h-[80%] w-[55%] rounded-full bg-asoebi-purple-700/35 blur-3xl"/><div data-motion-reveal className="relative mx-auto max-w-[1600px]"><p className="text-xs font-bold uppercase tracking-[.2em] text-asoebi-purple-300">Asoebi After Party</p><h2 className="font-display mt-6 max-w-6xl text-[clamp(3.8rem,9vw,9rem)] leading-[.82] tracking-[-.07em]">When the runway ends,<br/><span className="italic text-asoebi-purple-300">the night begins.</span></h2><div className="mt-12 grid gap-8 border-t border-white/20 pt-8 md:grid-cols-2"><p className="max-w-xl text-lg leading-8 text-white/65">The official networking and celebration experience of Asoebi Fashion Week.</p><div className="flex items-start justify-between gap-6"><p className="text-xs uppercase leading-6 tracking-[.15em] text-white/65">DJ line-up · Networking lounge<br/>Fashion awards ceremony</p><ArrowLink href="/after-party" inverse>Enter the night</ArrowLink></div></div></div></section>

    <section className="bg-brand px-5 py-28 text-white lg:px-10 lg:py-40"><div data-motion-reveal className="mx-auto flex max-w-[1600px] flex-col items-start justify-between gap-12 lg:flex-row lg:items-end"><h2 className="font-display max-w-5xl text-[clamp(3.5rem,8vw,8rem)] leading-[.82] tracking-[-.065em]">Be there when<br/>Asoebi takes<br/>the stage.</h2><Link href="/tickets" className="bg-white px-8 py-5 text-xs font-bold uppercase tracking-[.17em] text-brand">Get tickets ↗</Link></div></section>

    <section className="bg-asoebi-paper px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1600px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-muted">Partners</p>{partners.length ? <div>{partners.map((partner) => partner.name).join(" · ")}</div> : <p className="mt-8 border-y border-asoebi-ink/20 py-12 text-center font-display text-3xl italic text-asoebi-muted">Partner announcements are coming soon.</p>}</div></section>
  </HomeMotion>;
}
