import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { DesignSystemMotion } from "@/features/design-system/design-system-motion";

export const metadata: Metadata = {
  title: "Design System Notes",
  description: "An internal breakdown of the Asoebi Fashion Week design system.",
  robots: { index: false, follow: false, nocache: true },
};

const colors = [
  ["Asoebi violet", "#52239f", "oklch(40.23% 0.1838 293.56)", "rgba(82, 35, 159, 1)", "Identity, action and editorial emphasis"],
  ["Deep aubergine", "#2a1157", "oklch(26.46% 0.1167 292.92)", "rgba(42, 17, 87, 1)", "High-contrast moments and night energy"],
  ["Pale lilac", "#eee8f8", "oklch(94.03% 0.0223 302.93)", "rgba(238, 232, 248, 1)", "Atmosphere, grouping and soft separation"],
  ["Warm ivory", "#fff8ee", "oklch(98.18% 0.0152 77.07)", "rgba(255, 248, 238, 1)", "The primary canvas, warmer than clinical white"],
  ["Marigold", "#fbcd4f", "oklch(86.64% 0.1486 88.49)", "rgba(251, 205, 79, 1)", "Celebration, priority actions and highlights"],
  ["Coral", "#ef735d", "oklch(69.72% 0.1576 31.67)", "rgba(239, 115, 93, 1)", "A restrained supporting accent"],
] as const;

const motion = [
  ["Arrival", "Reveals hierarchy", "Large messages enter first; support follows only when it helps comprehension."],
  ["Continuity", "Connects states", "The navbar contracts, cards shuffle, and selected roles remain conceptually continuous."],
  ["Atmosphere", "Keeps fashion alive", "Slow image travel and the runway ribbon create energy without blocking reading."],
  ["Feedback", "Confirms intent", "Hover, selection, submission and download states answer an action quickly."],
] as const;

export default function DesignSystemPage() {
  return <DesignSystemMotion>
    <section className="px-5 pb-20 lg:px-10 lg:pb-32">
      <div className="mx-auto max-w-[1500px]">
        <div data-ds-meta className="flex items-center justify-between border-b border-asoebi-purple-200 pb-5 text-[10px] font-bold uppercase tracking-[.18em]"><span>Internal design notes</span><span>AFW · Living system</span></div>
        <div className="grid gap-12 pt-14 lg:grid-cols-[1.3fr_.7fr] lg:items-end">
          <div><p className="text-xs font-bold uppercase tracking-[.2em] text-brand">Tearing down the system</p><h1 className="font-display mt-5 text-[clamp(4.5rem,11vw,11rem)] leading-[.76] tracking-[-.07em]"><span className="block overflow-hidden"><span data-ds-hero-line className="block">Asoebi,</span></span><span className="block overflow-hidden"><span data-ds-hero-line className="block text-brand">by design.</span></span></h1></div>
          <div data-ds-hero-copy><p className="max-w-lg text-lg leading-8 text-asoebi-graphite">A practical record of how colour, type, space, imagery and motion work together to make Asoebi Fashion Week feel like a living fashion institution.</p><p className="mt-8 text-xs font-bold uppercase tracking-[.15em] text-asoebi-muted">Not a component catalogue. A set of decisions.</p></div>
        </div>
      </div>
    </section>

    <section data-ds-reveal className="bg-asoebi-purple-950 px-5 py-24 text-white lg:px-10 lg:py-36"><div className="mx-auto grid max-w-[1500px] gap-14 lg:grid-cols-[.65fr_1.35fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-gold-300">The premise</p><p className="font-display mt-5 text-4xl leading-[.98] tracking-[-.04em]">Fashion is personality.<br/>The interface is the frame.</p></div><div><p className="font-display text-[clamp(3.5rem,7vw,7rem)] leading-[.86] tracking-[-.055em]">Bright enough for celebration. Structured enough for authority. Fluid enough for cloth.</p><div className="mt-12 grid gap-5 sm:grid-cols-3">{[["Editorial, not ornamental"],["African, not generic luxury"],["Expressive, not exhausting"]].map(([label])=><div key={label} className="border-t border-white/25 pt-4"><p className="mt-8 font-bold">{label}</p></div>)}</div></div></div></section>

    <section className="px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand">Colour logic</p><div className="mt-5 grid gap-8 lg:grid-cols-2"><h2 className="font-display text-6xl leading-[.88] tracking-[-.055em] sm:text-8xl">Colour behaves like fabric.</h2><p className="max-w-xl self-end text-lg leading-8 text-asoebi-graphite">The system concentrates colour instead of flooding every surface. Ivory holds the page together, lilac groups related content, violet owns identity, and marigold marks moments worth noticing.</p></div><div data-ds-swatches className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{colors.map(([name,value,oklch,rgba,use])=><article key={value} style={{backgroundColor:value}} className={`flex aspect-[4/3] flex-col justify-between rounded-[1.5rem] p-6 shadow-[0_18px_50px_rgba(42,17,87,.10)] ${value==="#2a1157"||value==="#52239f" ? "text-white":"text-asoebi-purple-950"}`}><div className="space-y-1 font-mono text-[10px] font-bold uppercase tracking-[.06em]"><p>{value}</p><p>{oklch}</p><p>{rgba}</p></div><div><h3 className="font-display text-3xl tracking-[-.04em]">{name}</h3><p className="mt-2 max-w-xs text-sm opacity-65">{use}</p></div></article>)}</div></div></section>

    <section className="overflow-hidden bg-[#eee8f8] px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand">Typography</p><div className="mt-10 grid gap-12 lg:grid-cols-2"><div data-ds-specimen className="rounded-[2rem] bg-white p-8 shadow-[0_20px_60px_rgba(42,17,87,.10)] sm:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-muted">Bricolage Grotesque · personality</p><p className="font-display mt-10 text-7xl leading-[.82] tracking-[-.065em] sm:text-9xl">Cloth carries memory.</p><p className="font-display mt-10 text-3xl">Display, statements, chapters, collection names.</p></div><div data-ds-specimen className="rounded-[2rem] bg-asoebi-purple-950 p-8 text-white shadow-[0_20px_60px_rgba(42,17,87,.16)] sm:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-purple-300">Schibsted Grotesk · readability</p><p className="mt-10 max-w-lg text-2xl leading-9">Functional language stays composed and legible, from navigation and labels to schedules, forms and metadata.</p><div className="mt-14 space-y-4 border-t border-white/20 pt-7 text-sm"><p className="font-bold uppercase tracking-[.18em]">Navigation / 15px / 600</p><p className="leading-7 text-white/65">Body copy / 16 to 18px / generous leading</p><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-gold-300">Labels / 11 to 12px / deliberate tracking</p></div></div></div></div></section>

    <section className="px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand">Composition</p><h2 className="font-display mt-5 text-6xl leading-[.88] tracking-[-.055em]">Whitespace is part of the outfit.</h2></div><div data-ds-image-wrap className="relative aspect-[16/10] overflow-hidden rounded-[2rem] bg-white shadow-[0_24px_70px_rgba(42,17,87,.12)]"><Image data-ds-image src="/images/asoebi-hero-campaign.png" alt="Asoebi Fashion Week hero composition" fill sizes="(min-width:1024px) 65vw, 100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#fff8ee] via-[#fff8ee]/70 to-transparent"/><div className="absolute bottom-8 left-8 max-w-[8ch] font-display text-5xl leading-[.82] tracking-[-.055em] sm:text-8xl">Message first.<br/><span className="text-brand">Image in motion.</span></div></div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Scale","One dominant editorial message owns each chapter."],["Asymmetry","Offset columns create energy without disrupting semantic order."],["Media","Photography participates in layout; it is never decorative filler."]].map(([title,copy])=><article key={title} className="border-t border-asoebi-purple-300 pt-5"><h3 className="font-display text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-asoebi-graphite">{copy}</p></article>)}</div></div></section>

    <section data-ds-reveal className="bg-[#fff0bd] px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-gold-800">Motion has a job</p><h2 className="font-display mt-5 max-w-5xl text-6xl leading-[.86] tracking-[-.055em] sm:text-8xl">Move meaning,<br/>not everything.</h2><div className="mt-14 grid gap-4 lg:grid-cols-2">{motion.map(([title,role,description])=><article key={title} className="group rounded-[1.5rem] bg-white p-7 shadow-[0_16px_50px_rgba(97,58,13,.09)]"><div className="flex items-center justify-between"><h3 className="font-display text-4xl tracking-[-.04em]">{title}</h3><span className="grid size-10 place-items-center rounded-full bg-asoebi-purple-100 text-brand transition-transform transition-linear group-hover:rotate-45">↗</span></div><p className="mt-10 text-xs font-bold uppercase tracking-[.16em] text-brand">{role}</p><p className="mt-3 max-w-lg leading-7 text-asoebi-graphite">{description}</p></article>)}</div></div></section>

    <section className="px-5 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand">Component anatomy</p><h2 className="font-display mt-5 text-6xl tracking-[-.055em] sm:text-8xl">The invitation deck.</h2><div className="mt-14 grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div data-ds-card-stack className="relative min-h-[31rem] rounded-[2rem] bg-asoebi-purple-950 p-8"><div className="absolute inset-0 rounded-[2rem] bg-[url('/images/waitlist-collage.png')] bg-cover opacity-30"/><div className="absolute inset-8 translate-x-5 translate-y-5 rotate-3 rounded-[1.5rem] bg-[#f6b928] shadow-2xl"/><div className="absolute inset-8 translate-x-2 translate-y-2 -rotate-2 rounded-[1.5rem] bg-[#dcd0ff] shadow-2xl"/><div className="absolute inset-8 flex flex-col justify-between rounded-[1.5rem] bg-asoebi-purple-900 p-8 text-white shadow-2xl"><div className="flex justify-between text-xs font-bold uppercase tracking-[.18em]"><span>Asoebi Fashion Week</span><span className="grid size-10 place-items-center rounded-full bg-asoebi-gold-300 text-asoebi-purple-950">✺</span></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-white/55">Designer access</p><p className="font-display mt-3 text-5xl leading-[.9]">Your invitation is also an identity.</p></div><p className="border-t border-white/20 pt-5 text-[10px] font-bold uppercase tracking-[.16em]">Select · Personalise · Download</p></div></div><ol className="space-y-7">{[["Role first","Each audience receives a distinct colour, message and access identity."],["Selection as continuity","The chosen card moves to the front instead of disappearing and reappearing."],["A useful reward","Submission unlocks a personalised, downloadable object."],["One system, six expressions","Variation stays controlled through shared anatomy and type hierarchy."]].map(([title,copy],)=><li key={title} className="grid gap-4 border-b border-asoebi-purple-200 pb-7"><div><h3 className="font-display text-3xl">{title}</h3><p className="mt-2 text-sm leading-6 text-asoebi-graphite">{copy}</p></div></li>)}</ol></div></div></section>

    <section data-ds-reveal className="bg-asoebi-purple-950 px-5 py-24 text-white lg:px-10 lg:py-36"><div className="mx-auto max-w-[1500px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-asoebi-gold-300">Responsive behaviour</p><div className="mt-8 grid gap-12 lg:grid-cols-2"><h2 className="font-display text-6xl leading-[.86] tracking-[-.055em] sm:text-8xl">Recompose.<br/>Never just shrink.</h2><div className="grid gap-6 sm:grid-cols-3">{[["Desktop","Asymmetry, large type and layered media."],["Mobile","Semantic vertical flow and touch-first controls."],["Reduced motion","Final states remain; travel and atmosphere step away."]].map(([title,copy])=><div key={title} className="border-t border-white/25 pt-5"><h3 className="font-display text-3xl">{title}</h3><p className="mt-4 text-sm leading-6 text-white/60">{copy}</p></div>)}</div></div><div className="mt-20 flex flex-col justify-between gap-8 border-t border-white/20 pt-8 sm:flex-row sm:items-end"><p className="font-display max-w-3xl text-4xl leading-[.95]">If a choice does not strengthen fashion, clarity or culture, it does not belong in the system.</p><Link href="/" className="rounded-full bg-asoebi-gold-300 px-6 py-4 text-xs font-black uppercase tracking-[.14em] text-asoebi-purple-950">Return to the experience ↗</Link></div></div></section>
  </DesignSystemMotion>;
}
